// Generated by gencpp from file rviz_teleop_commander/groupChart.msg
// DO NOT EDIT!


#ifndef RVIZ_TELEOP_COMMANDER_MESSAGE_GROUPCHART_H
#define RVIZ_TELEOP_COMMANDER_MESSAGE_GROUPCHART_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rviz_teleop_commander
{
template <class ContainerAllocator>
struct groupChart_
{
  typedef groupChart_<ContainerAllocator> Type;

  groupChart_()
    : numHuman(0)
    , riskFactor(0.0)  {
    }
  groupChart_(const ContainerAllocator& _alloc)
    : numHuman(0)
    , riskFactor(0.0)  {
  (void)_alloc;
    }



   typedef int64_t _numHuman_type;
  _numHuman_type numHuman;

   typedef double _riskFactor_type;
  _riskFactor_type riskFactor;





  typedef boost::shared_ptr< ::rviz_teleop_commander::groupChart_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rviz_teleop_commander::groupChart_<ContainerAllocator> const> ConstPtr;

}; // struct groupChart_

typedef ::rviz_teleop_commander::groupChart_<std::allocator<void> > groupChart;

typedef boost::shared_ptr< ::rviz_teleop_commander::groupChart > groupChartPtr;
typedef boost::shared_ptr< ::rviz_teleop_commander::groupChart const> groupChartConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rviz_teleop_commander::groupChart_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rviz_teleop_commander::groupChart_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rviz_teleop_commander::groupChart_<ContainerAllocator1> & lhs, const ::rviz_teleop_commander::groupChart_<ContainerAllocator2> & rhs)
{
  return lhs.numHuman == rhs.numHuman &&
    lhs.riskFactor == rhs.riskFactor;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rviz_teleop_commander::groupChart_<ContainerAllocator1> & lhs, const ::rviz_teleop_commander::groupChart_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rviz_teleop_commander

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rviz_teleop_commander::groupChart_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rviz_teleop_commander::groupChart_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rviz_teleop_commander::groupChart_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rviz_teleop_commander::groupChart_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rviz_teleop_commander::groupChart_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rviz_teleop_commander::groupChart_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rviz_teleop_commander::groupChart_<ContainerAllocator> >
{
  static const char* value()
  {
    return "97d4b5d0a9eee48cf3fa2d456080f40e";
  }

  static const char* value(const ::rviz_teleop_commander::groupChart_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x97d4b5d0a9eee48cULL;
  static const uint64_t static_value2 = 0xf3fa2d456080f40eULL;
};

template<class ContainerAllocator>
struct DataType< ::rviz_teleop_commander::groupChart_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rviz_teleop_commander/groupChart";
  }

  static const char* value(const ::rviz_teleop_commander::groupChart_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rviz_teleop_commander::groupChart_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 numHuman\n"
"float64 riskFactor\n"
;
  }

  static const char* value(const ::rviz_teleop_commander::groupChart_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rviz_teleop_commander::groupChart_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.numHuman);
      stream.next(m.riskFactor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct groupChart_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rviz_teleop_commander::groupChart_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rviz_teleop_commander::groupChart_<ContainerAllocator>& v)
  {
    s << indent << "numHuman: ";
    Printer<int64_t>::stream(s, indent + "  ", v.numHuman);
    s << indent << "riskFactor: ";
    Printer<double>::stream(s, indent + "  ", v.riskFactor);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RVIZ_TELEOP_COMMANDER_MESSAGE_GROUPCHART_H
