
object_0:
  [
    {
      eight_point:
        [
          {id: 0, x: 1.456, y: -0.521, z: 0.854},
          {id: 1, x: 1.956, y: -0.603, z: 0.854},
          {id: 2, x: 2.035, y: -0.123, z: 0.854},
          {id: 3, x: 1.535, y: -0.041, z: 0.854},
          {id: 4, x: 1.456, y: -0.521, z: 0},
          {id: 5, x: 1.956, y: -0.603, z: 0},
          {id: 6, x: 2.035, y: -0.123, z: 0},
          {id: 7, x: 1.535, y: -0.041, z: 0}
        ]
    },
    {
      center_point: [{id: 'c', x: 1.74549, y: -0.322, z: 0.427}],
      class: 'chair',
      confidence: 0.9
    }
  ]

object_1:
  [
    {
      eight_point:
        [
          {id: 0, x: 0.888, y: 0.492, z: 0.859},
          {id: 1, x: 1.193, y: 0.089, z: 0.859},
          {id: 2, x: 1.573, y: 0.377, z: 0.859},
          {id: 3, x: 1.269, y: 0.779, z: 0.859},
          {id: 4, x: 0.888, y: 0.492, z: 0},
          {id: 5, x: 1.193, y: 0.089, z: 0},
          {id: 6, x: 1.573, y: 0.377, z: 0},
          {id: 7, x: 1.269, y: 0.779, z: 0}
        ]
    },
    {
      center_point: [{id: 'c', x: 1.23075, y: 0.43425, z: 0.4295}],
      class: 'chair',
      confidence: 0.8
    }
  ]

